import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const dialogPath = resolve(repoRoot, "src/app/canvas/components/canvas-node-seedance2-face-edit-dialog.tsx");
const source = readFileSync(dialogPath, "utf8");

assert.match(source, /export type CanvasSeedance2FaceEditPayload/);
assert.match(source, /onConfirm: \(payload: CanvasSeedance2FaceEditPayload\) => Promise<void> \| void;/);
assert.doesNotMatch(source, /onConfirm: \(payload: CanvasSeedance2FaceEditPayload\) => void;/);
assert.match(source, /export function CanvasNodeSeedance2FaceEditDialog/);
assert.match(source, /maskClosable=\{false\}/);
assert.match(source, /keyboard=\{false\}/);
assert.match(source, /closable=\{false\}/);
assert.match(source, /FACE_EDITOR_MODAL_WIDTH/);
assert.match(source, /关闭，不保存/);
assert.match(source, /确认保存并替换原图/);
assert.match(source, /Seedance2 人脸迁移/);
assert.match(source, /<Seedance2FaceEditDialogInner\s+key=\{dataUrl\}/);
assert.match(source, /function Seedance2FaceEditDialogInner/);
assert.match(source, /function readStrictImageMeta\(dataUrl: string\): Promise<ImageMeta>/);
assert.match(source, /const image = new Image\(\);/);
assert.match(source, /image\.onload = \(\) => \{\s*resolve\(\{\s*width: image\.naturalWidth,\s*height: image\.naturalHeight,\s*\}\);\s*\};/);
assert.match(source, /image\.onerror = \(\) => \{\s*reject\(new Error\("Image failed to load"\)\);\s*\};/);
assert.match(source, /readStrictImageMeta\(dataUrl\)[\s\S]*?\.catch\(/);
assert.match(source, /\.catch\(\(\) => \{\s*if \(!active\) return;\s*setImageMeta\(null\);\s*setSelection\(null\);[\s\S]*?setError\("读取图片尺寸失败，请重新选择图片"\);/);
assert.match(source, /if \(target === "selection"\) \{\s*setSelectedLayerId\(""\);\s*setActiveTool\("select"\);\s*\}/);

assert.match(source, /type DragState/);
assert.match(source, /startSelectionDrag/);
assert.match(source, /startLayerDrag/);
assert.match(source, /startResizeDrag/);
assert.match(source, /event\.shiftKey/);
assert.match(source, /setPointerCapture/);
assert.match(source, /captureTarget/);
assert.match(source, /releasePointerCapture/);
assert.match(source, /onLostPointerCapture=\{stopPointerDrag\}/);
assert.match(source, /rotateDeltaForBox/);
assert.match(source, /Math\.cos/);
assert.match(source, /Math\.sin/);
assert.match(source, /resizeHandles\.map/);
assert.match(source, /updateSelectedFaceLayer/);
assert.match(source, /旋转/);
assert.match(source, /composeSeedance2FaceEditImage/);
assert.match(source, /drawEllipsePath/);
assert.match(source, /borderRadius: "50%"/);
assert.doesNotMatch(source, /rounded-\[999px\]/);
assert.doesNotMatch(source, /borderRadius: "999px"/);
assert.match(source, /fillStyle = "#fff"/);
assert.match(source, /drawFaceLayer/);
assert.match(source, /function drawSourceSelectionPatch\(/);
assert.match(source, /sourceSelection\.rotation/);
assert.match(source, /drawGridLayer/);
assert.match(source, /createGridLinePlan/);
assert.match(source, /faceLayers:\s*FaceEditorFaceLayer\[\]/);
assert.match(source, /const faceLayers = layers\.filter\(\(layer\): layer is FaceEditorFaceLayer => layer\.kind === "face"\);/);
assert.match(source, /const gridLayers = layers\.filter\(\(layer\): layer is FaceEditorGridLayer => layer\.kind === "grid"\);/);
assert.match(source, /const \[previewDataUrl, setPreviewDataUrl\] = useState(?:<string>)?\((?:\(\) => )?""\);/);
assert.match(source, /useEffect\(\(\) => \{[\s\S]*?composeSeedance2FaceEditImage\(\{[\s\S]*?sourceDataUrl: dataUrl,[\s\S]*?imageSize: imageMeta,[\s\S]*?faceLayers,[\s\S]*?gridLayers,[\s\S]*?setPreviewDataUrl[\s\S]*?\}, \[dataUrl, imageMeta, layers\]\);/);
assert.match(source, /src=\{previewDataUrl \|\| dataUrl\}/);
assert.match(source, /faceLayers\.forEach\(\(layer\) => drawWhiteFill\(context, layer\.sourceSelection\)\);/);
assert.match(source, /faceLayers\.forEach\(\(layer\) => drawFaceLayer\(context, source, layer\)\);/);
assert.match(source, /const \[isSaving, setIsSaving\] = useState\(false\);/);
assert.match(source, /isEditorShortcutModifier\(event\)/);
assert.match(source, /event\.metaKey \|\| event\.ctrlKey/);
assert.match(source, /const key = event\.key\.toLowerCase\(\)/);
assert.match(source, /key !== "x" && key !== "v" && key !== "z"/);
assert.match(source, /if \(key === "x"\) \{[\s\S]*?createFaceLayer\(\)/);
assert.match(source, /if \(key === "v"\) \{[\s\S]*?createGridLayer\(\)/);
assert.match(source, /window\.addEventListener\("keydown", handleKeyDown, true\)/);
assert.match(source, /window\.removeEventListener\("keydown", handleKeyDown, true\)/);
assert.match(source, /Ctrl\/Cmd \+ X/);
assert.match(source, /Ctrl\/Cmd \+ V/);
assert.match(source, /if \(isSaving \|\| !imageMeta\) return;/);
assert.match(source, /const editedDataUrl = await composeSeedance2FaceEditImage\(\{/);
assert.match(source, /await onConfirm\(\{ dataUrl: editedDataUrl \}\);/);
assert.match(source, /setIsSaving\(true\);[\s\S]*?finally \{[\s\S]*?setIsSaving\(false\);/);
assert.match(source, /loading=\{isSaving\}/);
assert.match(source, /disabled=\{isSaving \|\| !imageMeta\}/);
assert.match(source, /const handleClose = \(\) => \{\s*if \(isSaving\) return;\s*onClose\(\);\s*\};/);
assert.ok((source.match(/disabled=\{isSaving\}/g) || []).length >= 2, "both close buttons should be disabled while saving");
assert.match(source, /onClick=\{handleClose\}[\s\S]*?disabled=\{isSaving\}/);
assert.match(source, /image\.crossOrigin = "anonymous";/);
assert.match(source, /function exportCanvasToPngDataUrl\(canvas: HTMLCanvasElement\): string/);
assert.match(source, /function moveLayerBox\(box: FaceEditorEllipseBox, delta: \{ dx: number; dy: number \}\): FaceEditorEllipseBox/);
assert.match(source, /function resizeLayerBox\([\s\S]*?lockCircle: boolean,[\s\S]*?\): FaceEditorEllipseBox/);
assert.match(source, /drag\.type === "selection-move"[\s\S]*?moveEllipseBox\(drag\.box, delta, imageSize\)/);
assert.match(source, /drag\.type === "layer-move"[\s\S]*?moveLayerBox\(drag\.box, delta\)/);
assert.match(source, /resizeLayerBox\(drag\.box, drag\.handle, rotateDeltaForBox\(delta, drag\.box\.rotation\), event\.shiftKey\)/);
assert.match(source, /SecurityError/);
assert.match(source, /图片跨域，无法导出；请先上传或使用本地图片/);
assert.match(source, /toDataURL\("image\/png"\)/);

assert.match(source, /type ActiveTool = "select" \| "move" \| "hand" \| "grid";/);
assert.match(source, /const DEFAULT_ZOOM = 100;/, "face editor should start from normal 100% before applying fit-to-view");
assert.match(source, /function calculateFaceEditorFitZoom\(/);
assert.match(source, /Math\.min\(1, availableWidth \/ imageSize\.width, availableHeight \/ imageSize\.height\)/);
assert.match(source, /setZoom\(nextFitZoom\)/, "the initial image should fit completely inside the editor viewport");
assert.match(source, /type: "viewport-pan"/);
assert.match(source, /const \[isCtrlPanning, setIsCtrlPanning\] = useState\(false\)/);
assert.match(source, /const handToolActive = activeTool === "hand" \|\| isCtrlPanning/);
assert.match(source, /\(!handToolActive && !event\.ctrlKey\) \|\| event\.button !== 0/);
assert.match(source, /event\.key === "Control"[\s\S]*?setIsCtrlPanning\(true\)/);
assert.match(source, /event\.key === "Control"[\s\S]*?setIsCtrlPanning\(false\)/);
assert.match(source, /addEventListener\("keyup", handleModifierKeyUp, true\)/);
assert.match(source, /addEventListener\("blur", clearModifierState\)/);
assert.match(source, /scrollLeft: viewport\.scrollLeft/);
assert.match(source, /scrollTop: viewport\.scrollTop/);
assert.match(source, /viewport\.scrollLeft = drag\.scrollLeft - \(event\.clientX - drag\.start\.x\)/);
assert.match(source, /viewport\.scrollTop = drag\.scrollTop - \(event\.clientY - drag\.start\.y\)/);
assert.doesNotMatch(source, /viewportOffset|translate3d/);
assert.match(source, /onPointerDownCapture=\{startViewportPan\}/);
assert.match(source, /onPointerMoveCapture=\{handlePointerMove\}/);
assert.match(source, /onPointerUpCapture=\{stopPointerDrag\}/);
assert.match(source, /interactive=\{!handToolActive\}/);
assert.match(source, /interactive \? "cursor-move" : "pointer-events-none"/);
assert.match(source, /cursor-grab active:cursor-grabbing/);
assert.match(source, /icon=\{<Hand className="size-4" \/>\}/);
assert.match(source, />\s*抓手\s*<\/ToolButton>/u);
assert.match(source, /const startSelectionDrag[\s\S]*?handToolActive \|\| event\.ctrlKey \|\| !selection/);
assert.match(source, /const startLayerDrag[\s\S]*?handToolActive \|\| event\.ctrlKey/);
assert.match(source, /const startResizeDrag[\s\S]*?handToolActive \|\| event\.ctrlKey/);
assert.match(source, /onClick=\{activateMoveTool\}/);
assert.match(source, /const activateMoveTool[\s\S]*?if \(selection\) \{\s*createFaceLayer\(\)/);
assert.match(source, /function hasVisibleFaceLayerChange\(/);
assert.match(source, /faceLayers\.length === 0 && gridLayers\.length === 0/);
assert.match(source, /!faceLayers\.some\(hasVisibleFaceLayerChange\)/);
assert.match(source, /const \{ message \} = App\.useApp\(\)/);
assert.ok((source.match(/message\.warning\(warning\)/g) || []).length >= 2, "both invalid save states should display a warning");
assert.match(source, /message\.error\(errorMessage\)/);
assert.match(source, /className="pointer-events-none absolute inset-0 h-full w-full select-none object-fill"/);
assert.match(source, /<ControlRow label="缩放"/u);
assert.match(source, /<Slider min=\{MIN_ZOOM\} max=\{MAX_ZOOM\}/);
assert.match(source, /const handleViewportWheel = useCallback\(\(event: WheelEvent\) =>/);
assert.match(source, /event\.deltaY < 0 \? 5 : -5/);
assert.match(source, /handleViewportWheel[\s\S]*?event\.preventDefault\(\);[\s\S]*?event\.stopPropagation\(\)/);
assert.match(source, /const wheelZoomFocusRef = useRef<WheelZoomFocus \| null>\(null\)/);
assert.match(source, /imageRatioX:[\s\S]*?imageRatioY:/);
assert.match(source, /viewport\.scrollLeft \+= focusedClientX - wheelFocus\.clientX/);
assert.match(source, /viewport\.scrollTop \+= focusedClientY - wheelFocus\.clientY/);
assert.match(source, /addEventListener\("wheel", handleViewportWheel, \{ passive: false \}\)/);
assert.match(source, /removeEventListener\("wheel", handleViewportWheel\)/);
assert.match(source, /滚轮缩放图片；抓手可拖动放大后的图片；/u);
assert.match(source, /按住 Ctrl 可临时使用抓手拖动/u);

console.log("seedance2 face editor dialog source tests passed");
