// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateState>;

export function FetchRelayModels(arg1:string,arg2:string):Promise<main.RelayModelsResponse>;

export function GetClientConfig():Promise<main.ClientConfig>;

export function GetUpdateState():Promise<main.UpdateState>;

export function SetAutoCheckUpdates(arg1:boolean):Promise<void>;

export function SetUpstreamURL(arg1:string):Promise<void>;

export function StartUpdate():Promise<void>;
