// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function FetchRelayModels(arg1, arg2) {
  return window['go']['main']['App']['FetchRelayModels'](arg1, arg2);
}

export function GetClientConfig() {
  return window['go']['main']['App']['GetClientConfig']();
}

export function GetUpdateState() {
  return window['go']['main']['App']['GetUpdateState']();
}

export function SetAutoCheckUpdates(arg1) {
  return window['go']['main']['App']['SetAutoCheckUpdates'](arg1);
}

export function SetUpstreamURL(arg1) {
  return window['go']['main']['App']['SetUpstreamURL'](arg1);
}

export function StartUpdate() {
  return window['go']['main']['App']['StartUpdate']();
}
